apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  config:
    tracing:
      backend: zipkin
      debug: "true"
      enable: "true"
      sample-rate: "1.0"
      zipkin-endpoint: "http://zipkin.knative-eventing.svc.cluster.local:9411/api/v2/spans"  
    config-features:
      authentication.oidc: "enabled"
      delivery-retryafter: "disabled"
      delivery-timeout: "enabled"
      eventtype-auto-create: "disabled"
      kreference-group: "disabled"
      kreference-mapping: "disabled"
      new-trigger-filters: "enabled"
      transport-encryption: "disabled"
